Renamed code directory to app
The name "code" as a directory was causing an exception "AttributeError: module 'code' has no attribute 'InteractiveInterpreter'" when flask was run with --debug.